input stream Timestamp(tp:u32, ts:u32)



{% with formula=formula %}
    {% include "formula.dl"%}
{%endwith%}


{% if formula.identifier == 0 %}
output relation Output(ts:u32, {{formula.sig | join(', ')}}) 
Output(ts, {{formula.args | join(', ')}}) :- Result_0({{formula.args | join(', ')}}), Timestamp_{{formula.identifier}}(tp,ts).
Output(ts, {{formula.args | join(', ')}}) :- Output-1(ts,{{formula.args | join(', ')}}).
{% endif%}
